### ISSUE TITLE
loading hooks error: %v open ./hooks: no such file or directory

### ISSUE THREAD

**Issue by jinjiao070** [Aur0ra-m/APIKiller#1]
在kali虚拟机里搭建时遇到以下错误：
ERRO[0000] [loading hooks error: %v open ./hooks: no such file or directory] 
panic: ([]fs.DirEntry) 0x15711c0

goroutine 1 [running]:
main.loadHooks({0x107f540, 0xc000120480})
        /root/桌面/APIKiller-main/main.go:225 +0x9e6
main.main()
        /root/桌面/APIKiller-main/main.go:53 +0xbf
exit status 2

在windows中不存在此问题 
内核版本为：5.18.0-kali7-amd64

**Comment by Aur0ra-m** [comment]
感谢师傅反馈。这边是因为git默认不上传空目录，导致hooks目录没有成功上传，目前已完成修复。你可以手动在根目录下创建hooks目录，也可以重新git clone更新后的项目
